name: make_test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            matrix:
                php: ['8.1']
                dependencies: ["liblapacke liblapacke-dev libopenblas0 libopenblas-dev libopenblas0 libopenblas-dev libgd-dev libgd3"]
                os: [ubuntu-latest]

        name: "PHP: ${{ matrix.php }} "

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@verbose
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: gd, numpower-Numpower/numpower@main
                  tools: phpize
              env:
                NUMPOWER_LINUX_LIBS: liblapacke liblapacke-dev libopenblas0 libopenblas-dev libopenblas0 libopenblas-dev libgd-dev libgd3
            - name: Compile Extension
              run: |
                  sudo apt-get install -y --no-install-recommends ${{ matrix.dependencies }}
                  phpize
                  ./configure
                  make

            - name: Execute tests
              run: make test
              env:
                  NDARRAY_FREEBUFFER: 1
                  USE_ZEND_ALLOC: 1
